"""
SQLite trade logger.
Records every signal, order submission, and fill to a local database.

Tables:
    signals  — every TradeSignal generated by the strategy
    orders   — every order submitted to Alpaca
    fills    — confirmed fills (polled from Alpaca)
    equity   — daily portfolio snapshots
"""
from __future__ import annotations

import sqlite3
import os
from datetime import datetime
from contextlib import contextmanager
from utils.logger import get_logger

logger = get_logger(__name__)

DB_PATH = os.getenv("DB_PATH", "db/zeno.db")


@contextmanager
def _conn():
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    con = sqlite3.connect(DB_PATH)
    con.row_factory = sqlite3.Row
    try:
        yield con
        con.commit()
    except Exception:
        con.rollback()
        raise
    finally:
        con.close()


def init_db():
    """Create tables if they don't exist. Safe to call on every startup."""
    with _conn() as con:
        con.executescript("""
            CREATE TABLE IF NOT EXISTS signals (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                ts          TEXT    NOT NULL,
                symbol      TEXT    NOT NULL,
                signal      TEXT    NOT NULL,
                confidence  REAL,
                reason      TEXT
            );

            CREATE TABLE IF NOT EXISTS orders (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                ts          TEXT    NOT NULL,
                symbol      TEXT    NOT NULL,
                side        TEXT    NOT NULL,
                qty         INTEGER NOT NULL,
                order_id    TEXT,
                status      TEXT,
                price       REAL
            );

            CREATE TABLE IF NOT EXISTS fills (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                ts          TEXT    NOT NULL,
                symbol      TEXT    NOT NULL,
                side        TEXT    NOT NULL,
                qty         INTEGER NOT NULL,
                fill_price  REAL    NOT NULL,
                order_id    TEXT
            );

            CREATE TABLE IF NOT EXISTS equity (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                ts              TEXT    NOT NULL,
                portfolio_value REAL    NOT NULL,
                cash            REAL    NOT NULL,
                open_positions  INTEGER NOT NULL
            );
        """)
    logger.info(f"Database initialised at {DB_PATH}")


def log_signal(symbol: str, signal: str, confidence: float, reason: str):
    with _conn() as con:
        con.execute(
            "INSERT INTO signals (ts, symbol, signal, confidence, reason) VALUES (?,?,?,?,?)",
            (datetime.utcnow().isoformat(), symbol, signal, confidence, reason),
        )


def log_order(symbol: str, side: str, qty: int, order_id: str | None,
              status: str, price: float | None):
    with _conn() as con:
        con.execute(
            "INSERT INTO orders (ts, symbol, side, qty, order_id, status, price) "
            "VALUES (?,?,?,?,?,?,?)",
            (datetime.utcnow().isoformat(), symbol, side, qty, order_id, status, price),
        )


def log_fill(symbol: str, side: str, qty: int, fill_price: float, order_id: str | None):
    with _conn() as con:
        con.execute(
            "INSERT INTO fills (ts, symbol, side, qty, fill_price, order_id) "
            "VALUES (?,?,?,?,?,?)",
            (datetime.utcnow().isoformat(), symbol, side, qty, fill_price, order_id),
        )


def log_equity(portfolio_value: float, cash: float, open_positions: int):
    with _conn() as con:
        con.execute(
            "INSERT INTO equity (ts, portfolio_value, cash, open_positions) VALUES (?,?,?,?)",
            (datetime.utcnow().isoformat(), portfolio_value, cash, open_positions),
        )


def get_recent_trades(limit: int = 50) -> list[dict]:
    with _conn() as con:
        rows = con.execute(
            "SELECT * FROM fills ORDER BY ts DESC LIMIT ?", (limit,)
        ).fetchall()
    return [dict(r) for r in rows]


def get_equity_history() -> list[dict]:
    with _conn() as con:
        rows = con.execute(
            "SELECT * FROM equity ORDER BY ts ASC"
        ).fetchall()
    return [dict(r) for r in rows]
